### ISSUE TITLE
weight problem

### ISSUE THREAD

**Issue by mgq1507** [jutanke/person_reid#2]
When load_model(), I have counted this problem?@jutanke Can you help me? Thank you!
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f25b52ed3962> in <module>()
     11 X, Y = m1501.get_train()
     12 
---> 13 model = reid.ReId()
     14 
     15 im1 = X[0]

~/gen/Re-ID/person_reid-master/reid/reid.py in __init__(self, root, url, name)
     28             dl.download(url, filepath)
     29 
---> 30         self.model = load_model(filepath)
     31 
     32     def predict(self, A, B):

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    417     f = h5dict(filepath, 'r')
    418     try:
--> 419         model = _deserialize_model(f, custom_objects, compile)
    420     finally:
    421         if opened_new_file:

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in _deserialize_model(f, custom_objects, compile)
    272                                                        original_keras_version,
    273                                                        original_backend,
--> 274                                                        reshape=False)
    275         if len(weight_values) != len(symbolic_weights):
    276             raise ValueError('Layer #' + str(k) +

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    680         weights = convert_nested_time_distributed(weights)
    681     elif layer.__class__.__name__ in ['Model', 'Sequential']:
--> 682         weights = convert_nested_model(weights)
    683 
    684     if original_keras_version == '1':

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in convert_nested_model(weights)
    668                     weights=weights[:num_weights],
    669                     original_keras_version=original_keras_version,
--> 670                     original_backend=original_backend))
    671                 weights = weights[num_weights:]
    672         return new_weights

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    680         weights = convert_nested_time_distributed(weights)
    681     elif layer.__class__.__name__ in ['Model', 'Sequential']:
--> 682         weights = convert_nested_model(weights)
    683 
    684     if original_keras_version == '1':

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in convert_nested_model(weights)
    656                     weights=weights[:num_weights],
    657                     original_keras_version=original_keras_version,
--> 658                     original_backend=original_backend))
    659                 weights = weights[num_weights:]
    660 

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    799             weights[0] = np.reshape(weights[0], layer_weights_shape)
    800         elif layer_weights_shape != weights[0].shape:
--> 801             weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
    802             if layer.__class__.__name__ == 'ConvLSTM2D':
    803                 weights[1] = np.transpose(weights[1], (3, 2, 0, 1))

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in transpose(a, axes)
    548 
    549     """
--> 550     return _wrapfunc(a, 'transpose', axes)
    551 
    552 

~/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     55 def _wrapfunc(obj, method, *args, **kwds):
     56     try:
---> 57         return getattr(obj, method)(*args, **kwds)
     58 
     59     # An AttributeError occurs if the object does not have

ValueError: axes don't match array

**Comment by mgq1507** [comment]
model = load_model('/home/dell/gen/weight/model_heavy_89acc.h5')
this code error

**Comment by jutanke** [comment]
What are your versions of tensorflow / keras?

**Comment by jutanke** [comment]
I will look into it tonight, thanks for reporting

**Comment by mgq1507** [comment]
> I will look into it tonight, thanks for reporting

Thank you very much!

**Comment by jutanke** [comment]
The model was trained with Keras 2.1.3 which, for some reason, seems to be incompatible with Keras 2.2.+. I will look into this further

**Comment by jutanke** [comment]
So, after investigating it seems like there were breaking changes in the DenseNet implementation of Keras. I now spoon-feed the weights to the model if it is not in a supported version which takes painfully long. However, the prediction does not properly work anymore.

Unfortunately, i will be quite busy for the foreseeable future so I would suggest to just train your own model using the train function. Hopefully, I can just train a model myself in the next couple of weeks.

So far

**Comment by mgq1507** [comment]
I have transfer the version to 2.1.3 and it works.
How to train can get the weight you offered?
Thank you.

**Comment by jutanke** [comment]
You can try the current new version. It should work with Keras 2.1.x but there seems to be a bug in Keras 2.2.x that prevents models from checkpoints to be loaded.

**Comment by jutanke** [comment]
There seems to be a problem with Keras 2.2.x and loading weights from checkpoints. So if you use Keras 2.1.x you should be fine. Furthermore, I retrained the model so now it should work quite a bit better. Simply re-install the library via pip:
```
pip install git+https://github.com/jutanke/person_reid.git
```

Then you can use it as before:
```python
import cv2
from reid import reid

im1 = cv2.cvtColor(cv2.imread('/path/to/file1.png'), cv2.COLOR_BGR2RGB)
im2 = cv2.cvtColor(cv2.imread('/path/to/file2.png'), cv2.COLOR_BGR2RGB)

# im1 / im2 can either be images or lists of images. In case of lists
# prediction is done item-wise

model = reid.ReId()
score = model.predict(im1, im2)
```

Good luck
