### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by fareesa9152** [jutanke/person_reid#5]
`IndexError                                Traceback (most recent call last)
<ipython-input-10-6d705d115988> in <module>()
     11 X, Y = m1501.get_train()
     12 
---> 13 model = reid.ReId()
     14 
     15 im1 = X[0]

8 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    939                                  str(weights[0].size) + '. ')
    940             weights[0] = np.reshape(weights[0], layer_weights_shape)
--> 941         elif layer_weights_shape != weights[0].shape:
    942             weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
    943             if layer.__class__.__name__ == 'ConvLSTM2D':

IndexError: list index out of range`

**Comment by jutanke** [comment]
Hey, please note that this library was developed using Python 3.6, numpy, Keras 2.1.3. and tensorflow 1.8. Which version of each of the libraries are you using?
Cheers

**Comment by fareesa9152** [comment]
Thank you, it worked...
